"""Report generation from StreakForge analysis output."""

import pandas as pd
from datetime import datetime
from pathlib import Path


def generate_report(kpis: dict, members_df: pd.DataFrame, report_date=None):
    """Generate structured text report from KPI analysis output.
    
    Args:
        kpis: Dictionary with keys like 'churn', 'retention', 'active', 'streak', etc.
        members_df: DataFrame with member data for additional analysis
        report_date: Date for report (defaults to today)
    
    Returns:
        str: Formatted text report with KPI summary, key findings, and recommendations
    """
    if report_date is None:
        report_date = datetime.now()
    
    lines = []
    
    # Header
    lines.append("=" * 70)
    lines.append("STREAKFORGE RETENTION INTELLIGENCE REPORT")
    lines.append("=" * 70)
    lines.append(f"Generated: {report_date:%Y-%m-%d %H:%M:%S}")
    lines.append("")
    
    # KPI Summary Section
    lines.append("== KEY PERFORMANCE INDICATORS SUMMARY ==")
    lines.append("")
    total_members = kpis.get("total_members", 0)
    active_members = kpis.get("active", 0)
    retention_pct = kpis.get("retention", 0.0)
    churn_pct = kpis.get("churn", 0.0)
    median_streak = kpis.get("streak", 0.0)
    
    lines.append(f"Total Members:        {total_members:,}")
    lines.append(f"Active Members (30d): {active_members:,} ({100*active_members/total_members:.1f}%)")
    lines.append(f"Retention Rate:       {retention_pct}%")
    lines.append(f"Churn Rate:           {churn_pct}%")
    lines.append(f"Median Streak Length: {median_streak:.0f} days")
    lines.append(f"Total Check-ins:      {kpis.get('visits', 0):,}")
    lines.append("")
    
    # Key Finding Section
    lines.append("== KEY FINDING ==")
    lines.append("")
    
    # Analyze churn trend
    churn_delta = kpis.get("churn_delta", 0.0)
    if churn_delta > 1.0:
        finding = f"CONCERN: Churn increased by {churn_delta:.1f} pts MoM (now {churn_pct}%)."
        severity = "HIGH"
    elif churn_delta < -1.0:
        finding = f"POSITIVE: Churn decreased by {abs(churn_delta):.1f} pts MoM (now {churn_pct}%)."
        severity = "IMPROVEMENT"
    else:
        finding = f"STABLE: Churn remained steady at {churn_pct}%."
        severity = "NORMAL"
    
    lines.append(f"[{severity}] {finding}")
    lines.append("")
    
    # Member composition analysis
    if not members_df.empty:
        if "membership_type" in members_df.columns:
            top_membership = members_df["membership_type"].value_counts().idxmax()
            top_membership_count = members_df["membership_type"].value_counts().max()
            lines.append(f"Top membership type: {top_membership} ({top_membership_count:,} members)")
        
        if "city" in members_df.columns:
            top_city = members_df["city"].value_counts().idxmax()
            top_city_count = members_df["city"].value_counts().max()
            lines.append(f"Largest city segment: {top_city} ({top_city_count:,} members)")
        
        lines.append("")
    
    # Recommended Actions Section
    lines.append("== RECOMMENDED ACTIONS ==")
    lines.append("")
    
    actions = []
    
    if churn_pct > 7.0:
        actions.append("1. URGENT: Churn exceeds 7% threshold. Launch retention campaign immediately.")
    elif churn_pct > 5.0:
        actions.append("1. Monitor: Churn trending upward. Schedule check-in with high-churn segments.")
    else:
        actions.append("1. Status: Churn under control. Continue current member engagement strategy.")
    
    if active_members < total_members * 0.3:
        actions.append("2. ENGAGEMENT: Less than 30% of members active in last 30 days. Review onboarding.")
    elif active_members < total_members * 0.5:
        actions.append("2. ENGAGEMENT: 30-50% active. Targeted re-engagement campaign recommended.")
    else:
        actions.append("2. ENGAGEMENT: Strong engagement (50%+). Maintain current activity level.")
    
    if median_streak < 20:
        actions.append("3. PROGRAM: Median streak below 20 days. Introduce streak milestones/rewards.")
    else:
        actions.append("3. PROGRAM: Strong median streak. Highlight consistency in marketing materials.")
    
    for action in actions:
        lines.append(action)
    
    lines.append("")
    lines.append("=" * 70)
    lines.append("Report generated by StreakForge Analytics Engine")
    lines.append("=" * 70)
    
    return "\n".join(lines)


def generate_report_csv(kpis: dict, members_df: pd.DataFrame, report_date=None):
    """Generate CSV report with metrics breakdown.
    
    Args:
        kpis: Dictionary with KPI values
        members_df: DataFrame with member data
        report_date: Date for report (defaults to today)
    
    Returns:
        str: CSV formatted string with metrics
    """
    if report_date is None:
        report_date = datetime.now()
    
    # Create CSV content
    csv_lines = []
    csv_lines.append("Metric,Value,Unit")
    csv_lines.append(f"Report Date,{report_date:%Y-%m-%d},date")
    csv_lines.append(f"Total Members,{kpis.get('total_members', 0)},count")
    csv_lines.append(f"Active Members,{kpis.get('active', 0)},count")
    csv_lines.append(f"Retention Rate,{kpis.get('retention', 0)},percent")
    csv_lines.append(f"Churn Rate,{kpis.get('churn', 0)},percent")
    csv_lines.append(f"Median Streak,{kpis.get('streak', 0)},days")
    csv_lines.append(f"Total Check-ins,{kpis.get('visits', 0)},count")
    csv_lines.append(f"Retention Delta,{kpis.get('retention_delta', 0)},points")
    csv_lines.append(f"Churn Delta,{kpis.get('churn_delta', 0)},points")
    csv_lines.append(f"Active Delta,{kpis.get('active_delta', 0)},percent")
    
    return "\n".join(csv_lines)


def generate_report_html(kpis: dict, members_df: pd.DataFrame, report_date=None):
    """Generate HTML report for email delivery.
    
    Args:
        kpis: Dictionary with KPI values
        members_df: DataFrame with member data
        report_date: Date for report (defaults to today)
    
    Returns:
        str: HTML formatted report
    """
    if report_date is None:
        report_date = datetime.now()
    
    total_members = kpis.get("total_members", 0)
    active_members = kpis.get("active", 0)
    retention_pct = kpis.get("retention", 0.0)
    churn_pct = kpis.get("churn", 0.0)
    median_streak = kpis.get("streak", 0.0)
    churn_delta = kpis.get("churn_delta", 0.0)
    
    # Determine alert color
    churn_color = "#d32f2f" if churn_pct > 7.0 else "#f57c00" if churn_pct > 5.0 else "#388e3c"
    
    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; color: #333; }}
            .container {{ max-width: 800px; margin: 0 auto; padding: 20px; }}
            .header {{ background: #1976d2; color: white; padding: 20px; border-radius: 4px; }}
            .section {{ margin: 20px 0; padding: 15px; border-left: 4px solid #1976d2; background: #f5f5f5; }}
            .kpi {{ display: inline-block; margin: 10px 20px 10px 0; }}
            .kpi-value {{ font-size: 24px; font-weight: bold; color: #1976d2; }}
            .kpi-label {{ font-size: 12px; color: #666; }}
            .alert {{ background: {churn_color}; color: white; padding: 10px; border-radius: 4px; margin: 10px 0; }}
            .action {{ margin: 10px 0; padding: 10px; background: white; border-left: 3px solid #1976d2; }}
            .footer {{ text-align: center; color: #999; font-size: 12px; margin-top: 30px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>StreakForge Retention Report</h1>
                <p>Generated {report_date:%B %d, %Y at %H:%M}</p>
            </div>
            
            <div class="section">
                <h2>KPI Summary</h2>
                <div class="kpi">
                    <div class="kpi-value">{total_members:,}</div>
                    <div class="kpi-label">Total Members</div>
                </div>
                <div class="kpi">
                    <div class="kpi-value">{active_members:,}</div>
                    <div class="kpi-label">Active (30d)</div>
                </div>
                <div class="kpi">
                    <div class="kpi-value">{retention_pct}%</div>
                    <div class="kpi-label">Retention</div>
                </div>
                <div class="kpi">
                    <div class="kpi-value">{churn_pct}%</div>
                    <div class="kpi-label">Churn</div>
                </div>
                <div class="kpi">
                    <div class="kpi-value">{median_streak:.0f}</div>
                    <div class="kpi-label">Median Streak (days)</div>
                </div>
            </div>
            
            <div class="section">
                <h2>Key Finding</h2>
                <div class="alert">
    """
    
    if churn_delta > 1.0:
        html += f"⚠️ Churn increased by {churn_delta:.1f} pts MoM. Immediate attention required."
    elif churn_delta < -1.0:
        html += f"✓ Churn improved by {abs(churn_delta):.1f} pts MoM. Great progress!"
    else:
        html += f"→ Churn stable at {churn_pct}%. Continue current strategy."
    
    html += f"""
                </div>
            </div>
            
            <div class="section">
                <h2>Recommended Actions</h2>
    """
    
    if churn_pct > 7.0:
        html += '<div class="action">🚨 URGENT: Launch retention campaign. Churn exceeds safe threshold.</div>'
    elif churn_pct > 5.0:
        html += '<div class="action">📋 Review high-churn segments and schedule engagement outreach.</div>'
    
    if active_members < total_members * 0.3:
        html += '<div class="action">👥 Low engagement detected. Review onboarding and re-engagement strategy.</div>'
    
    if median_streak < 20:
        html += '<div class="action">🎯 Introduce streak milestones and rewards to encourage consistency.</div>'
    
    html += """
            </div>
            
            <div class="footer">
                <p>This is an automated report from StreakForge Analytics</p>
                <p>Questions? Contact your retention intelligence team</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    return html
