[theme]
primaryColor = "#2980B9"
backgroundColor = "#F7F9FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2C3E50"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 25

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"